export { default as Home } from './home/Home.jsx'
export { default as Admin } from './admin/Admin.jsx'
export { default as Cart } from './cart/Cart.jsx'
export { default as OrderHistory } from './OrderHistory/OrderHistory.jsx'
export { default as Login } from './auth/Login.jsx'
export { default as Register } from './auth/Register.jsx'
export { default as Reset } from './auth/Reset.jsx'